### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by RichSu95** [Leedeng/SauvolaNet#3]
Hello @Leedeng,

Would it be possible to provide a demo on how to train the model?
Thank you!

**Comment by mohamadmansourX** [comment]
Hello,
I was able to build some wrappers and easy to use [Configuration File](https://github.com/mohamadmansourX/SauvolaNet-Training/blob/master/docs/Training_Config.md) for training the model.
Just play with the [Config file](https://github.com/mohamadmansourX/SauvolaNet-Training/blob/master/docs/Training_Config.md) and run `$python train.py` and you're done.
Hope I can merge it with this Github later!
https://github.com/mohamadmansourx/SauvolaNet-Training

**Comment by RichSu95** [comment]
@mohamadmansourX Thanks a lot! I shall check it out.
